# org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dkotlin.daemon.jvm.options=-Xmx2048m
# android.useAndroidX=true
# android.enableJetifier=true

# JVM settings (خفيفة وتكفي للـ build)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Kotlin compiler memory
kotlin.daemon.jvm.options=-Xmx1024m

# Optimize Gradle
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# AndroidX flags
android.useAndroidX=true
android.enableJetifier=true